name: Continuous Deployment
on: [workflow_dispatch]
jobs:
  Deploy-API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
      - uses: docker/setup-buildx-action@v2.0.0
      - run: (cd api/todo; echo "${{ secrets.SSL_DOMAIN_CRT }}" | base64 --decode >> domain.crt)
      - run: (cd api/todo; echo "${{ secrets.SSL_PRIVATE_KEY }}" | base64 --decode >> private.key)
      - run: (cd api/todo; npm ci)
      - run: (cd api/todo; npm run build)
      - run: (cd api/todo; docker build -t public.ecr.aws/f4k7k9n9/rmbr-api .)
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - run: (cd api/todo; docker push public.ecr.aws/f4k7k9n9/rmbr-api)

  Deploy-Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
      - uses: docker/setup-buildx-action@v2.0.0
      - run: (cd client/web; printf "REACT_APP_API_URL=${{ secrets.API_URL }}\nREACT_APP_CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env)
      - run: (cd client/web; echo "${{ secrets.SSL_DOMAIN_CRT }}" | base64 --decode >> domain.crt)
      - run: (cd client/web; echo "${{ secrets.SSL_PRIVATE_KEY }}" | base64 --decode >> private.key)
      - run: (cd client/web; npm ci)
      - run: (cd client/web; npm run build)
      - run: (cd client/web; docker build -t public.ecr.aws/f4k7k9n9/rmbr-web .)
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - run: (cd client/web; docker push public.ecr.aws/f4k7k9n9/rmbr-web)
