name: Continuous Deployment
on: [workflow_dispatch]
jobs:
  Deploy-API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
      - uses: docker/setup-buildx-action@v2.0.0
      - run: (cd api/todo; npm ci)
      - run: (cd api/todo; npm run build)
