name: Continuous Integration
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.5.0
        with: 
          node-version: 16
      - run: (cd client/web; npm ci)
