name: Continuous Integration
on: [push]
jobs:
  Test-API:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.5.0
        with: 
          node-version: 16
      - run: (cd api/todo; npm ci)
      - run: (cd api/todo; npm run test)
      
  Test-Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.5.0
        with: 
          node-version: 16
      - run: (cd client/web; npm ci)
      - run: (cd client/web; npm run test)
